language: php

php:
    - 7.0

install:
    - ls ../
    - php -n bin/composer.phar require satooshi/php-coveralls

before_script:
    - ls ../
    - php -n bin/composer.phar self-update
    - php -n bin/composer.phar update
    - mkdir -p build/logs
    
script:
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls
