language: php

php:
    - 7.0

install:
    - ls $HOME
    - ls $HOME/.composer
    - ls $HOME/.composer/bin
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer.phar require satooshi/php-coveralls

before_script:
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer.phar require self-update
    - php -n ~/.phpenv/versions/$(phpenv version-name)/bin/composer.phar require update

script:
    - phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls
